---
title: "Assignment 1: Introduction"
author: "Hannah Wudke"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.


## 1) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I have no experience with R or Git. I have broad experience in data analytics, such as basic statistics and work on ArcGIS Pro, however I have no coding experience at all. I have zero formal or informal training.

2. Are there any components of the course about which you feel confident?

> Answer: Yes, I think that the course has been set-up in a way that will fully support me learning how to use R, and how to code, with zero experience. I feel that by the end of the course, I will have the skills that I need! 

3. Are there any components of the course about which you feel apprehensive?

> Answer: Because I have no R or Git experience, I am apprehensive about running into issues on either platform and not being able to troubleshoot them myself. Git in particular seems to have a steep learning curve. However, I think once I am used to the platforms, this will go much more smoothly. 


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: https://github.com/h-wud/EDE_Fall2024

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
